# Generated by Django 3.1.5 on 2021-02-05 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_friends_profilepicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccounts',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profilepicture',
            name='image',
            field=models.ImageField(default='avatar.jpg', upload_to='profile'),
        ),
    ]
